parameters:
  buildConfiguration: 'Release'
  artifactName: ''


jobs:
 - job: BuildLinux
   pool:
     vmImage: 'ubuntu-latest'

   steps:
   - task: DotNetCoreCLI@2
     inputs:
       command: 'restore'
       projects: '**/*.csproj'
       feedsToUse: 'select'
     displayName: 'restaurer les packages'
   - task: DotNetCoreCLI@2
     inputs:
       command: 'build'
       projects: '**/*.csproj'
       arguments: '--configuration $(buildConfiguration)'
     displayName: 'Génération de la solution'

   - task: DotNetCoreCLI@2
     inputs:
       command: 'test'
       projects: '**/*Tests.csproj'
       arguments: '--configuration $(buildConfiguration)'
     displayName: 'Exécution des tests unitaires'

   - task: DotNetCoreCLI@2
     inputs:
       command: 'publish'
       publishWebProjects: true
       arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
     displayName: 'Génération du package de publication'

   - task: PublishBuildArtifacts@1
     inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: $(artifactName)
       publishLocation: 'Container'
     displayName: 'Publication du package dans Azure DevOps'